name: Build and publish document

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - synchronize
jobs:

  publishPRDraft:
    name: Build and publish draft
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts with the docker image
      run: docker-compose up
    - name: Package built file
      run: |
        mkdir -p build
        cp draft-ietf-gnap-core-protocol.html build/index.html
    - name: Deploy draft to Netlify
      uses: South-Paw/action-netlify-deploy@v1.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_ID }}
        build-dir: './build'
        draft: true
        comment-on-pull-request: true

  publishEditorsCopy:
    name: Build and publish editors' draft
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build the artifacts with the docker image
      run: docker-compose up
    - name: Package built file
      run: |
        mkdir -p build
        cp draft-ietf-gnap-core-protocol.html build/index.html
    - name: Deploy draft to Netlify
      uses: South-Paw/action-netlify-deploy@v1.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_ID }}
        build-dir: './build'
        comment-on-commit: true
